// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateMissionReducer from "../create_mission_reducer";
import EstimateEmissionsReducer from "../estimate_emissions_reducer";
import EvaluateComplianceReducer from "../evaluate_compliance_reducer";
import RecordTrajectoryResultReducer from "../record_trajectory_result_reducer";
import RecordWeatherSnapshotReducer from "../record_weather_snapshot_reducer";

export type CreateMissionParams = __Infer<typeof CreateMissionReducer>;
export type EstimateEmissionsParams = __Infer<typeof EstimateEmissionsReducer>;
export type EvaluateComplianceParams = __Infer<typeof EvaluateComplianceReducer>;
export type RecordTrajectoryResultParams = __Infer<typeof RecordTrajectoryResultReducer>;
export type RecordWeatherSnapshotParams = __Infer<typeof RecordWeatherSnapshotReducer>;

