// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  seed: __t.i64(),
  massKg: __t.f64(),
  fuelKg: __t.f64(),
  lifespanYears: __t.f64(),
  targetAltitudeKm: __t.f64(),
  targetInclinationDeg: __t.f64(),
  crossSectionAreaM2: __t.f64(),
  dragCoefficient: __t.f64(),
  ispS: __t.f64(),
  modelVersion: __t.string(),
};
