// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  missionId: __t.u64().primaryKey().name("mission_id"),
  analogVehicle: __t.string().name("analog_vehicle"),
  co2EKg: __t.f64().name("co_2_e_kg"),
  noxKg: __t.f64().name("nox_kg"),
  blackCarbonKg: __t.f64().name("black_carbon_kg"),
  altitudeLayer: __t.string().name("altitude_layer"),
  payloadShare: __t.f64().name("payload_share"),
  estimatedAt: __t.timestamp().name("estimated_at"),
});
