// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  vehicle: __t.string().primaryKey(),
  meanAltitudeKm: __t.f64().name("mean_altitude_km"),
  co2EKgPerLaunch: __t.f64().name("co_2_e_kg_per_launch"),
  noxKgPerLaunch: __t.f64().name("nox_kg_per_launch"),
  blackCarbonKgPerLaunch: __t.f64().name("black_carbon_kg_per_launch"),
  payloadCapacityKg: __t.f64().name("payload_capacity_kg"),
  altitudeLayer: __t.string().name("altitude_layer"),
});
