// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  seed: __t.i64(),
  massKg: __t.f64().name("mass_kg"),
  fuelKg: __t.f64().name("fuel_kg"),
  lifespanYears: __t.f64().name("lifespan_years"),
  targetAltitudeKm: __t.f64().name("target_altitude_km"),
  targetInclinationDeg: __t.f64().name("target_inclination_deg"),
  crossSectionAreaM2: __t.f64().name("cross_section_area_m_2"),
  dragCoefficient: __t.f64().name("drag_coefficient"),
  ispS: __t.f64().name("isp_s"),
  modelVersion: __t.string().name("model_version"),
});
