// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  missionId: __t.u64(),
  kp: __t.option(__t.f64()),
  f107: __t.option(__t.f64()),
  solarWindSpeedKmS: __t.option(__t.f64()),
  solarWindDensity: __t.option(__t.f64()),
  solarWindTemperatureK: __t.option(__t.f64()),
  source: __t.string(),
  retrievedAt: __t.string(),
};
