// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  missionId: __t.u64().primaryKey().name("mission_id"),
  compliant: __t.bool(),
  reasonCode: __t.string().name("reason_code"),
  deorbitTimeYears: __t.f64().name("deorbit_time_years"),
  regulationsConsidered: __t.u32().name("regulations_considered"),
  evaluatedAt: __t.timestamp().name("evaluated_at"),
});
