// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const DebrisRegulation = __t.object("DebrisRegulation", {
  htmlUrl: __t.string(),
  title: __t.string(),
  publicationDate: __t.string(),
  abstract: __t.string(),
  syncedAt: __t.timestamp(),
});
export type DebrisRegulation = __Infer<typeof DebrisRegulation>;

export const EmissionsEstimate = __t.object("EmissionsEstimate", {
  missionId: __t.u64(),
  analogVehicle: __t.string(),
  co2EKg: __t.f64(),
  noxKg: __t.f64(),
  blackCarbonKg: __t.f64(),
  altitudeLayer: __t.string(),
  payloadShare: __t.f64(),
  estimatedAt: __t.timestamp(),
});
export type EmissionsEstimate = __Infer<typeof EmissionsEstimate>;

export const LaunchCatalogEntry = __t.object("LaunchCatalogEntry", {
  vehicle: __t.string(),
  meanAltitudeKm: __t.f64(),
  co2EKgPerLaunch: __t.f64(),
  noxKgPerLaunch: __t.f64(),
  blackCarbonKgPerLaunch: __t.f64(),
  payloadCapacityKg: __t.f64(),
  altitudeLayer: __t.string(),
});
export type LaunchCatalogEntry = __Infer<typeof LaunchCatalogEntry>;

export const Mission = __t.object("Mission", {
  id: __t.u64(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  seed: __t.i64(),
  massKg: __t.f64(),
  fuelKg: __t.f64(),
  lifespanYears: __t.f64(),
  targetAltitudeKm: __t.f64(),
  targetInclinationDeg: __t.f64(),
  crossSectionAreaM2: __t.f64(),
  dragCoefficient: __t.f64(),
  ispS: __t.f64(),
  modelVersion: __t.string(),
});
export type Mission = __Infer<typeof Mission>;

export const RegulatoryCompliance = __t.object("RegulatoryCompliance", {
  missionId: __t.u64(),
  compliant: __t.bool(),
  reasonCode: __t.string(),
  deorbitTimeYears: __t.f64(),
  regulationsConsidered: __t.u32(),
  evaluatedAt: __t.timestamp(),
});
export type RegulatoryCompliance = __Infer<typeof RegulatoryCompliance>;

export const TrajectoryResult = __t.object("TrajectoryResult", {
  missionId: __t.u64(),
  totalRuns: __t.u32(),
  passes: __t.u32(),
  failures: __t.u32(),
  probabilityPass: __t.f64(),
  probabilityFail: __t.f64(),
  baselinePassed: __t.bool(),
  baselineFailureReasons: __t.array(__t.string()),
  availableDeltaVMs: __t.f64(),
  requiredDeltaVMs: __t.f64(),
  propellantRemainingKg: __t.f64(),
  finalAltitudeKm: __t.f64(),
  computedAt: __t.timestamp(),
});
export type TrajectoryResult = __Infer<typeof TrajectoryResult>;

export const WeatherSnapshot = __t.object("WeatherSnapshot", {
  missionId: __t.u64(),
  kp: __t.option(__t.f64()),
  f107: __t.option(__t.f64()),
  solarWindSpeedKmS: __t.option(__t.f64()),
  solarWindDensity: __t.option(__t.f64()),
  solarWindTemperatureK: __t.option(__t.f64()),
  source: __t.string(),
  retrievedAt: __t.string(),
});
export type WeatherSnapshot = __Infer<typeof WeatherSnapshot>;

