// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  missionId: __t.u64().primaryKey().name("mission_id"),
  kp: __t.option(__t.f64()),
  f107: __t.option(__t.f64()).name("f_107"),
  solarWindSpeedKmS: __t.option(__t.f64()).name("solar_wind_speed_km_s"),
  solarWindDensity: __t.option(__t.f64()).name("solar_wind_density"),
  solarWindTemperatureK: __t.option(__t.f64()).name("solar_wind_temperature_k"),
  source: __t.string(),
  retrievedAt: __t.string().name("retrieved_at"),
});
